from .registry import CLASS_REGISTRY
from .ivfpq import IndexIVFPQ
from .ivfsq import IndexIVFSQ
from .ivfpqr import IndexIVFPQR
from .ivfhnsq import IndexIVF_HNSW
from .ivflat import IndexIVFFlat
from .ivfLocalSearchQuantizer import IndexIVFLocalSearchQuantizer
from .ivfResidualQuantizer import IndexIVFResidualQuantizer
from .load import load_faiss_index